name: NetworkNest
version: "1.0.0"
slug: networknest
description: Network monitoring dashboard with 3D visualization
url: https://github.com/networknest/homeassistant-integration
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
init: false
hassio_api: true
hassio_role: default
homeassistant_api: true
host_network: false
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: Web interface
webui: http://[HOST]:[PORT:3000]
panel_icon: mdi:network
panel_title: NetworkNest
options:
  log_level: info
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssl: bool
  certfile: str
  keyfile: str
image: ghcr.io/networknest/addon-{arch}