name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  validate-hacs:
    runs-on: ubuntu-latest
    name: Validate with HACS
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration

  validate-hassfest:
    runs-on: ubuntu-latest
    name: Validate with hassfest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: hassfest validation
        uses: home-assistant/actions/hassfest@master